services:
  - type: web
    name: mini-ecommerce
    repo: https://github.com/Joao19Paulo/mini-ecommerce
    env: node
    plan: free
    branch: master
    buildCommand: npm install
    startCommand: npm start
    rootDir: .
    autoDeploy: true
